### ISSUE TITLE
pulumi crashing with terraform stacktrace on ResourceServer creations

### ISSUE THREAD

**Issue by kopernic-pl** [auth0/terraform-provider-auth0#846]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Defined new, completely independent resourceServer using Pulumi.
```
const cfg2 = {
  name: 'xxx',
  identifier: 'https://SBAP2/',
  signingAlg: 'RS256',
} as ResourceServerArgs;

export const sbapResourceServer2 = new auth0.ResourceServer('some-other-resserver', cfg2);
```

I get an exception and failed deployment

```
     panic: value is null
    goroutine 267 [running]:
    github.com/hashicorp/go-cty/cty.Value.AsString({{{0x103d9ae68?, 0x14000192171?}}, {0x0?, 0x0?}})
        /home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:1176 +0x114
    github.com/auth0/terraform-provider-auth0/internal/auth0/resourceserver.isManagementAPI({{{0x103d9aff0?, 0x1400078d320?}}, {0x103bab160?, 0x14000300510?}})
        /home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.50.2/internal/auth0/resourceserver/resource.go:299 +0x64
    github.com/auth0/terraform-provider-auth0/internal/auth0/resourceserver.expandResourceServer(0x140003ccc00)
        /home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.50.2/internal/auth0/resourceserver/resource.go:251 +0x120
    github.com/auth0/terraform-provider-auth0/internal/auth0/resourceserver.createResourceServer({0x103d9b220, 0x14000285ce0}, 0x12b84acf8?, {0x103bd9ae0?, 0x1400078e1c0?})
        /home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.50.2/internal/auth0/resourceserver/resource.go:152 +0x5c
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x14000664c40, {0x103d9acf8, 0x1047a4f60}, 0xd?, {0x103bd9ae0, 0x1400078e1c0})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230710100801-03a71d0fca3d/helper/schema/resource.go:738 +0xe8
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000664c40, {0x103d9acf8, 0x1047a4f60}, 0x0, 0x140003cc980, {0x103bd9ae0, 0x1400078e1c0})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230710100801-03a71d0fca3d/helper/schema/resource.go:869 +0x860
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0x1400007c120?, {0x0?, 0x14000891580?, 0x103d2d820?}}, {0x10386d591, 0x15}, {0x0?, 0x0}, {0x103da25e0?, 0x140003cc980})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.59.0/pkg/tfshim/sdk-v2/provider.go:100 +0x140
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0x14000207600, {0x103d9b178?, 0x140008899b0?}, 0x140000510e0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.59.0/pkg/tfbridge/provider.go:752 +0x4ec
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x103d9b178, 0x140008899b0}, {0x103cc13e0?, 0x140000510e0})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.81.0/proto/go/provider_grpc.pb.go:573 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x103d9b178, 0x14000889680}, {0x103cc13e0, 0x140000510e0}, 0x14000790700, 0x140000a6c18)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x103d4bd00?, 0x14000207600}, {0x103d9b178, 0x14000889680}, 0x14000285180, 0x140006b0080)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.81.0/proto/go/provider_grpc.pb.go:575 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x1400039e000, {0x103da3b60, 0x1400009b1e0}, 0x140007539e0, 0x14000541e90, 0x10475ef60, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0xc04
    google.golang.org/grpc.(*Server).handleStream(0x1400039e000, {0x103da3b60, 0x1400009b1e0}, 0x140007539e0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0x7c4
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 45
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:980 +0x154

```

### Expectation

Resource is created

### Reproduction

Pulumi Code and stack trace above, but I was unable to reproduce this in a minimal one-resource environment.

### Auth0 Terraform Provider version

0.50.2

### Terraform version

Pulumi 3.84.0

**Comment by kopernic-pl** [comment]
Details of the resource that pulumi wants to create
```
 auth0:index/resourceServer:ResourceServer: (create)
        [urn=urn:pulumi:integration::pulumi-auth0::auth0:index/resourceServer:ResourceServer::some-other-resserver]
        [provider=urn:pulumi:integration::pulumi-auth0::pulumi:providers:auth0::default_2_24_2::2f0c838d-cd69-4ac2-bdc1-25fd7c6bfc2a]

        identifier: "https://SBAP2/"
        name      : "xxx"
        signingAlg: "RS256"
```

**Comment by sergiught** [comment]
Hey @kopernic-pl 👋🏻 

Thanks for taking the time to raise this with us. The issue is caused by a lack of support of `GetRawState()` within the pulumni terraform bridge, so thus not an issue with this provider. Please see https://github.com/pulumi/pulumi-auth0/issues/285#issuecomment-1716813284. 

However we can look into making some adjustments within our codebase to facilitate the integration. I don't have an exact ETA of when we'll be able to tho but I'll keep you updated within this issue.

**Comment by kopernic-pl** [comment]
Thx for prompt respoinse @sergiught , I've just noticed that - as well that there is patched release of pulumi-auth0 that is one hour old.
